name: ASF-code-quality

on:
  - push

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

permissions:
  checks: write
  contents: write
  pull-requests: write
  security-events: write

jobs:
  main:
    environment: qa-qodana
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7
      with:
        show-progress: false

    - name: Run Qodana scan
      uses: JetBrains/qodana-action@v2024.1.5
      with:
        args: --config,.github/qodana.yaml,--property=idea.headless.enable.statistics=false
        pr-mode: false
        upload-result: true
      env:
        QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

    - name: Report Qodana results to GitHub
      uses: github/codeql-action/upload-sarif@v3.25.10
      with:
        sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
