name: ASF-docker-ci

on: [push, pull_request]

env:
  PLATFORMS: linux/amd64,linux/arm,linux/arm64

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        file: [Dockerfile, Dockerfile.Service]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4
      with:
        submodules: recursive

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0

    - name: Build ${{ matrix.configuration }} Docker image from ${{ matrix.file }}
      uses: docker/build-push-action@v2.7.0
      with:
        context: .
        file: ${{ matrix.file }}
        platforms: ${{ env.PLATFORMS }}
        build-args: |
          CONFIGURATION=${{ matrix.configuration }}
          STEAM_TOKEN_DUMPER_TOKEN=${{ secrets.STEAM_TOKEN_DUMPER_TOKEN }}
