name: ASF-docker-ci

on: [push, pull_request]

env:
  PLATFORMS: linux/amd64,linux/arm,linux/arm64

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image from Dockerfile
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: ${{ env.PLATFORMS }}

    - name: Build Docker image from Dockerfile.Service
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.Service
        platforms: ${{ env.PLATFORMS }}
